[package]
name = "asn1_parser"
version = "0.1.0"
authors = ["Aaron Power <a.power@1aim.com>"]
edition = "2018"

[dependencies]
pest = "2.0.2"
pest_derive = "2.0.1"
failure = "0.1.3"
clap = "2.32.0"
derefable = "0.1"
unwrap_to = "0.1.0"
variation = "0.1.0"
