[package]
name = "asn1-core"
version = "0.1.0"
authors = ["meh. <meh@1aim.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"

num-traits  = "0.2"
num-integer = "0.1"
bigint  = { version = "0.2", package = "num-bigint" }
failure = "0.1.5"
derefable = "0.1.0"
