[package]
name = "dasn1-pest"
version = "0.1.1"
authors = ["Erin Power <e.power@dac.eu>"]
edition = "2018"
description = "A pest grammar for the ASN.1 notation language."
license = "MIT/Apache-2.0"


[dependencies]
pest = "2"
pest_derive = "2"
