[package]
name    = "asn1"
version = "0.1.0"
authors = ["meh. <meh@1aim.com>"]
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
bitvec  = "0.6"
chrono  = "0.4"
decorum = "0.1"
bytes   = "0.4"

num-traits  = "0.2"
num-integer = "0.1"
bigint  = { version = "0.2", package = "num-bigint" }

asn1_derive = { path = "../asn1_derive", version = "0.1", optional = true }

[dev-dependencies]
asn1_derive = { path = "../asn1_derive" }

[features]
derive = ["asn1_derive"]
