[package]
name    = "serde_asn1"
version = "0.1.0"
authors = ["meh. <meh@1aim.com>"]
license = "MIT/Apache-2.0"

[dependencies]
asn1 = { path = "../asn1", version = "0.1" }
serde = "1"
bytes = { version = "0.4", features = ["serde"] }

[dev-dependencies]
compiletest_rs = "0.3"
serde_derive = "1.0"
